services:
  backend:
    build:
      context: .
      dockerfile: ../docker/backend/Dockerfile
    tty: true
    volumes:
      - ./backend:/backend
    working_dir: /backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: ../docker/frontend/Dockerfile
    tty: true
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    ports:
      - "3000:3000"
